name: CI
on:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build-and-push.yml
    with:
      image_tag: ${{ github.sha }}
      push: false
      upload: false
